### ISSUE TITLE
感谢阿里巴巴的开源！请问如何搭建环境编译固件走出第一步；

### ISSUE THREAD

**Issue by xuhongv** [alibaba/genie-bt-mesh-stack#2]
- 作为阿里巴巴的粉丝，感谢阿里巴巴的开源！请问如何搭建环境编译固件走出第一步；

**Comment by huangjunlan** [comment]
可以参照alios things开发环境先安装编译环境。

**Comment by huangjunlan** [comment]
感谢对阿里巴巴的支持，可以参照以下文档搭建编译环境
[linux](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Linux-Environment-Setup)
[windows](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-Windows-Environment-Setup)
[mac](https://github.com/alibaba/AliOS-Things/wiki/AliOS-Things-MAC-Environment-Setup)
