### ISSUE TITLE
建议从git版本管理中移除一些python执行时的中间文件

### ISSUE THREAD

**Issue by haoran-zhan** [alibaba/genie-bt-mesh-stack#4]
建议移除build/cmd/win32/Python27/Lib目录下的python执行时的中间文件，扩展名为.pyc。编译的时候这些文件会重新生成，不需要被git管理。
建议移除的文件如下：
UserDict.pyc
_abcoll.pyc
_weakrefset.pyc
abc.pyc
codecs.pyc
copy_reg.pyc
__init__.pyc
aliases.pyc
gbk.pyc
fnmatch.pyc
functools.pyc
genericpath.pyc
glob.pyc
__init__.pyc
decoder.pyc
encoder.pyc
scanner.pyc
linecache.pyc
locale.pyc
ntpath.pyc
os.pyc
re.pyc
site.pyc
sre_compile.pyc
sre_constants.pyc
sre_parse.pyc
stat.pyc
struct.pyc
sysconfig.pyc
traceback.pyc
types.pyc
warnings.pyc

**Comment by huangjunlan** [comment]
感谢分享
